# Generated by Django 2.2.4 on 2019-08-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_desc', models.TextField()),
                ('task_com_status', models.BooleanField(default=False)),
            ],
        ),
    ]
